Repository 3DAsset-eCommerce/3D-BE, pull requests merged in 2023-06, with the labels that each got.

#26 chore : #1 Entity 일부 수정
  src/main/java/com/phoenix/assetbe/model/asset/Asset.java
  src/main/java/com/phoenix/assetbe/model/asset/Category.java
  src/main/java/com/phoenix/assetbe/model/asset/Tag.java
Labels: Completed, Low

#69 bugfix : #30 로그인시 데이터 추가
  src/main/java/com/phoenix/assetbe/controller/UserController.java
  src/main/java/com/phoenix/assetbe/dto/user/UserRequest.java
  src/main/java/com/phoenix/assetbe/dto/user/UserResponse.java
  src/main/java/com/phoenix/assetbe/service/UserService.java
  src/test/java/com/phoenix/assetbe/controller/UserControllerTest.java
  src/test/java/com/phoenix/assetbe/service/UserServiceTest.java
Labels: In Progress

#71 setting : #37 새로운 이미지 적용하도록 변경
  .github/workflows/dev.yml
  .github/workflows/main.yml
Labels: In Progress

#73 fix #18 #21 에셋 리뷰 에러 수정
  src/main/java/com/phoenix/assetbe/dto/asset/ReviewRequest.java
  src/main/java/com/phoenix/assetbe/model/asset/AssetRepository.java
  src/main/java/com/phoenix/assetbe/model/asset/ReviewRepository.java
  src/main/java/com/phoenix/assetbe/model/wish/WishListRepository.java
  src/test/java/com/phoenix/assetbe/controller/ReviewControllerTest.java
Labels: Review Needed, Bug

#80 feat : #24 하위 카테고리별 에셋 조회
  src/main/java/com/phoenix/assetbe/controller/AssetController.java
  src/main/java/com/phoenix/assetbe/model/asset/AssetQueryRepository.java
  src/main/java/com/phoenix/assetbe/service/AssetService.java
  src/test/java/com/phoenix/assetbe/controller/AssetControllerTest.java
Labels: Completed, Medium

#81 test : #15 장바구니 조회 테스트 수정 및 추가
  src/test/java/com/phoenix/assetbe/controller/CartControllerTest.java
Labels: Completed, Test

#84 [chore] Asset 엔티티 수정
  src/main/generated/com/phoenix/assetbe/model/asset/QAsset.java
  src/main/java/com/phoenix/assetbe/core/dummy/DataInit.java
  src/main/java/com/phoenix/assetbe/core/dummy/DummyEntity.java
  src/main/java/com/phoenix/assetbe/model/asset/Asset.java
Labels: Completed, Critical

#86 feat : 장바구니 테스트 수정
  src/main/java/com/phoenix/assetbe/dto/cart/CartResponse.java
  src/main/java/com/phoenix/assetbe/model/cart/CartRepository.java
  src/test/java/com/phoenix/assetbe/controller/CartControllerTest.java
  src/test/java/com/phoenix/assetbe/service/CartServiceTest.java
Labels: Review Needed, Completed, Critical

#87 chore : 더미 엔티티 수정
  src/main/java/com/phoenix/assetbe/core/dummy/DummyEntity.java
Labels: Review Needed, Completed

#88 feat : 주문하기 테스트 수정
  src/test/java/com/phoenix/assetbe/controller/OrderControllerTest.java
  src/test/java/com/phoenix/assetbe/service/OrderServiceTest.java
Labels: Review Needed, Completed, Low

#90 chore : 더미 엔티티 수정
  src/main/java/com/phoenix/assetbe/core/dummy/DataInit.java
  src/test/java/com/phoenix/assetbe/core/config/MyTestSetUp.java
Labels: Review Needed, Bug

#93 chore : 더미 엔티티 수정
  src/main/java/com/phoenix/assetbe/core/dummy/DataInit.java
Labels: Completed

#94 chore : 더미 엔티티 수정
  src/main/java/com/phoenix/assetbe/core/dummy/DataInit.java
  src/test/java/com/phoenix/assetbe/core/config/MyTestSetUp.java
Labels: Critical

#97 feat : #79 주문 서비스 테스트
  src/main/java/com/phoenix/assetbe/model/order/OrderRepository.java
  src/main/java/com/phoenix/assetbe/service/OrderService.java
  src/test/java/com/phoenix/assetbe/service/OrderServiceTest.java
Labels: Completed, Test

#112 refactor : #110 더미 데이터 수정 및 추가
  src/main/java/com/phoenix/assetbe/controller/UserController.java
  src/main/java/com/phoenix/assetbe/core/dummy/DataInit.java
  src/main/java/com/phoenix/assetbe/core/dummy/DummyEntity.java
  src/main/java/com/phoenix/assetbe/dto/asset/ReviewRequest.java
  src/main/java/com/phoenix/assetbe/dto/cart/CartRequest.java
  src/main/java/com/phoenix/assetbe/dto/order/OrderRequest.java
  src/main/java/com/phoenix/assetbe/dto/user/UserRequest.java
  src/main/java/com/phoenix/assetbe/dto/user/UserResponse.java
  src/main/java/com/phoenix/assetbe/model/user/User.java
  src/main/java/com/phoenix/assetbe/service/UserService.java
  src/test/java/com/phoenix/assetbe/controller/AssetControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/CartControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/OrderControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/ReviewControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/UserControllerTest.java
  src/test/java/com/phoenix/assetbe/core/config/MyTestSetUp.java
  src/test/java/com/phoenix/assetbe/service/UserServiceTest.java
Labels: Review Needed, Test

#113 setting : https 설정
  src/main/resources/application-dev.yml
  src/main/resources/keystore.p12
Labels: Critical

#114 setting : https 설정 테스트
  src/main/resources/application-dev.yml
Labels: Critical

#121 setting : 관리자 더미 데이터 추가
  src/main/java/com/phoenix/assetbe/core/dummy/DataInit.java
  src/main/java/com/phoenix/assetbe/core/dummy/DummyEntity.java
  src/test/java/com/phoenix/assetbe/core/config/MyTestSetUp.java
Labels: Low

#126 feat : #78 주문 내역 조회 날짜 추가
  src/main/generated/com/phoenix/assetbe/model/order/QOrder.java
  src/main/generated/com/phoenix/assetbe/model/user/QUser.java
  src/main/java/com/phoenix/assetbe/controller/OrderController.java
  src/main/java/com/phoenix/assetbe/model/order/OrderQueryRepository.java
  src/main/java/com/phoenix/assetbe/service/OrderService.java
  src/test/java/com/phoenix/assetbe/controller/OrderControllerTest.java
  src/test/java/com/phoenix/assetbe/service/OrderServiceTest.java
Labels: Review Needed, Enhancement

#127 fix : #18 에셋 리뷰 보기 - 에셋에 리뷰가 없으면 빈값으로 응답
  src/main/java/com/phoenix/assetbe/service/ReviewService.java
Labels: Low

#128 fix : #78 주문 내역 조회 테스트 수정
  src/test/java/com/phoenix/assetbe/service/OrderServiceTest.java
Labels: Bug

#139 refactor : #100 관리자 서비스 수정
  src/main/java/com/phoenix/assetbe/service/AdminService.java
Labels: Review Needed

#156 refactor : 에러 수정, 환경변수 설정 변경
  .github/workflows/dev.yml
  .gitignore
  build.gradle
  src/main/java/com/phoenix/assetbe/core/config/MailProperties.java
  src/main/java/com/phoenix/assetbe/core/config/MyMailConfig.java
  src/main/java/com/phoenix/assetbe/core/config/S3Config.java
  src/main/java/com/phoenix/assetbe/core/util/MailUtils.java
  src/main/java/com/phoenix/assetbe/service/S3Service.java
  src/main/resources/application.yml
Labels: Review Needed, Completed

#166 feat : #104 관리자 에셋 추가 - 기능 구현, 통합테스트
  src/main/java/com/phoenix/assetbe/controller/AdminController.java
  src/main/java/com/phoenix/assetbe/dto/admin/AdminRequest.java
  src/main/java/com/phoenix/assetbe/model/asset/Asset.java
  src/main/java/com/phoenix/assetbe/service/AdminService.java
  src/main/resources/application.yml
  src/test/java/com/phoenix/assetbe/controller/AdminControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/AssetControllerTest.java
Labels: Review Needed, Test

#176 feat : 관리자 에셋 파일 등록/삭제 수정
  src/main/java/com/phoenix/assetbe/controller/AdminController.java
  src/main/java/com/phoenix/assetbe/dto/admin/AdminRequest.java
  src/main/java/com/phoenix/assetbe/dto/user/UserResponse.java
  src/main/java/com/phoenix/assetbe/service/S3Service.java
Labels: Review Needed, Completed, High

#177 refactor : #91 내 에셋 검색 수정 및 추가
  src/main/java/com/phoenix/assetbe/model/asset/MyAssetQueryRepository.java
  src/test/java/com/phoenix/assetbe/controller/UserControllerTest.java
Labels: Review Needed

#209 docs : #178 API 명세서 작성
  src/docs/asciidoc/api-docs.adoc
  src/main/generated/com/phoenix/assetbe/model/user/QUser.java
  src/main/resources/application.yml
  src/main/resources/static/docs/api-docs.html
  src/test/java/com/phoenix/assetbe/controller/AdminControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/AssetControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/CartControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/CategoryControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/OrderControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/ReviewControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/UserControllerTest.java
  src/test/java/com/phoenix/assetbe/controller/WishControllerTest.java
Labels: Review Needed
